# Supabase Configuration for FitWithPari
# Local development and deployment configuration

project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://your-production-domain.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_nonce = true

[auth.sms]
enable_signup = false
enable_confirmations = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.google]
enabled = true
client_id = "your-google-oauth-client-id"
secret = "your-google-oauth-secret"
redirect_uri = "https://your-supabase-project.supabase.co/auth/v1/callback"

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
# Optimized for fitness platform with frequent updates
max_header_length = 4096

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[storage.buckets.user-avatars]
public = true
file_size_limit = "5MiB"
allowed_mime_types = ["image/jpeg", "image/png", "image/gif", "image/webp"]

[storage.buckets.exercise-content]
public = true
file_size_limit = "50MiB"
allowed_mime_types = ["image/jpeg", "image/png", "image/gif", "image/webp", "video/mp4", "video/webm"]

[storage.buckets.session-recordings]
public = false
file_size_limit = "500MiB"
allowed_mime_types = ["video/mp4", "video/webm", "audio/mp3", "audio/wav"]

[inbucket]
enabled = true
port = 54324
# SMTP server for testing emails

[functions.realtime-session-manager]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.email-notifications]
verify_jwt = true

[edge-runtime]
policy = "per_request"

[analytics]
enabled = false
port = 54327

[experimental]
webhooks = true